1.Sentences
2.One hot Representation-- index from the dictionary
3.Onhot Repre----> Embedding layer Keras to form Embedding Matrix
4.Embedding matrix
vocab_size=10000, dimension=10
if we give index of 2000(Word) it will get coverted into dimension of 10 vector
        man  women  child  king   queen
gender  -1     1      0   -0.92   0.93  
royal 

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\91600\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\91600\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\91600\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framewo

In [2]:
###Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
#Vocabulary size that is total number of unique words in the text + 1 (for padding)
voc_size = 10000

One Hot representation

In [ ]:
#One hot representation of the sentences that is converting the words into numbers based on the index in the vocabulary list
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[9508, 6806, 5768, 7149], [9508, 6806, 5768, 3408], [9508, 5279, 5768, 9401], [6067, 9596, 7296, 9109, 8791], [6067, 9596, 7296, 9109, 5057], [5728, 9508, 5617, 5768, 8533], [1156, 1874, 2425, 9109]]


Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [ ]:
#Here we are padding the sentences to make them of same length. We are using pre padding that is adding zeros at the beginning of the sentences. We are also specifying the maximum length of the sentences as 8. If the sentences are less than 8 then it will add zeros at the beginning and if the sentences are more than 8 then it will truncate the sentences from the beginning.
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9508 6806 5768 7149]
 [   0    0    0    0 9508 6806 5768 3408]
 [   0    0    0    0 9508 5279 5768 9401]
 [   0    0    0 6067 9596 7296 9109 8791]
 [   0    0    0 6067 9596 7296 9109 5057]
 [   0    0    0 5728 9508 5617 5768 8533]
 [   0    0    0    0 1156 1874 2425 9109]]


In [ ]:
#Creating the model and adding the embedding layer. 
# The embedding layer takes the vocabulary size, the dimension of the embedding and the input length as parameters. 
# The input length is the length of the sentences after padding. The embedding layer will convert the one hot representation of the sentences into dense vectors of fixed size. 
# The dimension of the embedding is the size of the dense vectors that we want to create for each word in the vocabulary. 
# The embedding layer will learn the weights of the dense vectors during the training process.
#Below we consider the dimension of the embedding as 15 that is we want to create dense vectors of size 15 for each word in the vocabulary.
dim=15

In [ ]:
#Below here we are creating the model and adding the embedding layer. We are also compiling the model with adam optimizer and mean squared error as the loss function.
#Embedding layer will take the vocabulary size, the dimension of the embedding and the input length as parameters. 
#The input length is the length of the sentences after padding. The embedding layer will convert the one hot representation of the sentences into dense vectors of fixed size. 
#The dimension of the embedding is the size of the dense vectors that we want to create for each word in the vocabulary. 
#The embedding layer will learn the weights of the dense vectors during the training process.
#And finally we are printing the summary of the model and the output of the model for the embedded documents.
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\91600\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 449ms/step
[[[ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202
    0.00842609  0.01184658 -0.00775087  0.02415187 -0.02206247
   -0.00237995  0.04742617 -0.04739143 -0.03433185 -0.02247335]
  [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202
    0.00842609  0.01184658 -0.00775087  0.02415187 -0.02206247
   -0.00237995  0.04742617 -0.04739143 -0.03433185 -0.02247335]
  [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202
    0.00842609  0.01184658 -0.00775087  0.02415187 -0.02206247
   -0.00237995  0.04742617 -0.04739143 -0.03433185 -0.02247335]
  [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202
    0.00842609  0.01184658 -0.00775087  0.02415187 -0.02206247
   -0.00237995  0.04742617 -0.04739143 -0.03433185 -0.02247335]
  [-0.04514324 -0.00707488  0.04178245  0.00214205  0.02702547
   -0.03632627  0.00985998  0.02848883 -0.04256867 -0.04205769
   -0.02253145 -0.0156762  -0.01599034  0.00981622  0.0320742 ]
  [ 0.01562

In [ ]:
#The sentence at index 0 is 'the glass of milk' and the one hot representation of this sentence is [1, 2, 3, 4] and after padding it becomes [0, 0, 0, 1, 2, 3, 4] and the output of the model for this sentence is a dense vector of size 15 for each word in the sentence. So the output for this sentence will be a matrix of size (8, 15) where 8 is the length of the sentence after padding and 15 is the dimension of the embedding.
#that means it will create a dense vector of size 15 for each word in the sentence and the total number of words in the sentence after padding is 8. So the output will be a matrix of size (8, 15) for each sentence in the embedded documents.
embedded_docs[0]

array([   0,    0,    0,    0, 9508, 6806, 5768, 7149], dtype=int32)

In [ ]:
#Here we are printing the output of the model for the first sentence in the embedded documents. The output will be a matrix of size (8, 15) where 8 is the length of the sentence after padding and 15 is the dimension of the embedding.
#each word in the sentence will be represented as a dense vector of size 15 and the total number of words in the sentence after padding is 8. So the output will be a matrix of size (8, 15) for the first sentence in the embedded documents.
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
[[ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202  0.00842609
   0.01184658 -0.00775087  0.02415187 -0.02206247 -0.00237995  0.04742617
  -0.04739143 -0.03433185 -0.02247335]
 [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202  0.00842609
   0.01184658 -0.00775087  0.02415187 -0.02206247 -0.00237995  0.04742617
  -0.04739143 -0.03433185 -0.02247335]
 [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202  0.00842609
   0.01184658 -0.00775087  0.02415187 -0.02206247 -0.00237995  0.04742617
  -0.04739143 -0.03433185 -0.02247335]
 [ 0.00706352  0.0032776  -0.03449382  0.03835898  0.01634202  0.00842609
   0.01184658 -0.00775087  0.02415187 -0.02206247 -0.00237995  0.04742617
  -0.04739143 -0.03433185 -0.02247335]
 [-0.04514324 -0.00707488  0.04178245  0.00214205  0.02702547 -0.03632627
   0.00985998  0.02848883 -0.04256867 -0.04205769 -0.02253145 -0.0156762
  -0.01599034  0.00981622  0.0320742 ]
 [ 0.01562745 -0.00184443  